/* -*- Mode: C; tab-width: 8; indent-tabs-mode: t; c-basic-offset: 8 -*- */
/*
    Grig:  Gtk+ user interface for the Hamradio Control Libraries.

    Copyright (C)  2001-2006  Alexandru Csete.

    Authors: Alexandru Csete <csete@users.sourceforge.net>

    Comments, questions and bugreports should be submitted via
    http://sourceforge.net/projects/groundstation/
    More details can be found at the project home page:

            http://groundstation.sourceforge.net/
 
    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.
  
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
  
    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the
          Free Software Foundation, Inc.,
	  59 Temple Place, Suite 330,
	  Boston, MA  02111-1307
	  USA
*/
/** \file grig-debug.c
 *  \brief Manage debug messages.
 *
 * The functions in this file are used to log debug messages generated by
 * hamlib and grig itself. The debug messages are printed on stderr and
 * saved into a file, if the debug handler has been initialised with a file
 * name.
 */
#include <glib.h>
#include <glib/gi18n.h>
#include <hamlib/rig.h>
#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif
#include "grig-debug.h"


static gchar      *logfname = NULL;
static GIOChannel *logfile  = NULL;


/** \brief Initialise debug handler
 *  \param filename File name of log file or NULL.
 *
 * This function initialises the debug handler so that it is ready to
 * manage debug messages coming from hamlib. If logfile is not NULL, the
 * debug messages will be saved to this file as well.
 */
void
grig_debug_init  (gchar *filename)
{
        gchar *msg;


        if (filename != NULL) {
                /*** FIXME: open file for write/append ***/
        }

        /* set debug handler */
        rig_set_debug_callback (grig_debug_cb, NULL);
        
        /* send debug message to indicate readiness of debug handler */
        msg = g_strdup_printf (_("GRIG:%s: Debug handler initialised.\n"),
                               __FUNCTION__);
        rig_debug (RIG_DEBUG_VERBOSE, msg);
        g_free (msg);
}


/** \brief Close debug handler.
 *
 * This function cleans up the debug handler. Any further debug messages
 * will be handled by hamlib.
 */
void
grig_debug_close ()
{
        gchar *msg;

        /* send a final debug message */
        msg = g_strdup_printf (_("GRIG:%s: Shutting down debug handler.\n"),
                               __FUNCTION__);
        rig_debug (RIG_DEBUG_VERBOSE, msg);
        g_free (msg);

        /* remove debug handler */
        rig_set_debug_callback (NULL, NULL);

        /* close log file if open */
}


int
grig_debug_cb    (enum rig_debug_level_e debug_level,
                  rig_ptr_t user_data,
                  const char *fmt,
                  va_list ap)
{

	gchar          *msg;       /* formatted debug message */
	gchar         **msgv;      /* debug message line by line */
	guint           numlines;  /* the number of lines in the message */
	guint           i;
        GTimeVal        curtime;   /* current time (same as struct timeval) */


	/* create character string and split it in case
	   it is a multi-line message */
	msg = g_strdup_vprintf (fmt, ap);

	/* remove trailing \n */
	g_strchomp (msg);

	/* split the message in case it is a multiline message */
	msgv = g_strsplit_set (msg, "\n", 0);
	numlines = g_strv_length (msgv);

	g_print ("%d: %s\n", debug_level, msg);
	g_free (msg);


	/* get the time */
        g_get_current_time (&curtime);

	/* for each line in msgv, print the line to stderr
           and save into logfile.
	*/
	for (i = 0; i < numlines; i++) {
	}


	g_strfreev (msgv);
	
	return RIG_OK;

}


/** \brief Get the name of the current log file.
 *  \return The name of the current log file or NULL.
 *
 * The function returns the name of the currently use log file or NULL
 * if the debug messages are not saved to file. In case of non NULL return
 * value, the function returns a newly allocated string that should be freed
 * by the caller when no longer needed.
 */
gchar *
grig_debug_get_log_file ()
{
        if (logfname != NULL) {
                return g_strdup (logfname);
        }
        else {
                return NULL;
        }
}
